name: Semgrep

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}

  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}

  # Scan on direct commits to main/master:
  push:
    branches:
      - main
      - master
    # The paths section ensures that a direct commit on the `semgrep.yml` triggers a full scan.
    # The scan for direct commits will happen for the files you want to monitor. 
    paths:
      - '**/*'  # Monitors all files (this will trigger diff scan for all commits, not just `semgrep.yml`)

  # Schedule the CI job to run on a regular basis:
  schedule:
    - cron: '20 17 * * *'  # Every day at 17:20 UTC
    # You can adjust this to fit your schedule timing

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      # Fetch project source with GitHub Actions Checkout.
      - uses: actions/checkout@v4

      - name: Mark the directory as safe for Git
        run: |
          git config --global --add safe.directory /__w/Newone/Newone
      # Check if this is a direct commit to main (full scan) or a pull request (diff scan):
      - name: Run diff or full scan based on context
        run: |
          # Check if it's a direct commit to main/master branch
          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "Direct commit to main/master branch detected."
            BASELINE=$(git rev-parse HEAD~1)
            echo "baseline commit: $BASELINE"
            echo "GITHUB_REF: $SEMGREP_GITHUB_REF"
            echo "HEAD: $(git rev-parse HEAD)"
            semgrep ci --baseline-commit="$BASELINE" --verbose
          elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            # It's a PR, perform a diff scan
            echo "PR detected, running diff scan..."
            semgrep ci --baseline-commit="$BASELINE" --verbose
          else
            echo "No matching commit or PR detected."
          fi
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
